const teamMappings = {
  // AUS Conference
  "acadia": "Axemen",
  "acadia axemen": "Axemen",
  "acadia axewomen": "Axewomen",
  "dalhousie": "Tigers",
  "dal": "Tigers",
  "dalhousie tigers": "Tigers",
  "cape breton": "Capers",
  "cbu": "Capers",
  "cape breton capers": "Capers",
  "memorial": "Sea-Hawks",
  "mun": "Sea-Hawks",
  "memorial sea-hawks": "Sea-Hawks",
  "saint mary's": "Huskies",
  "saint marys": "Huskies",
  "st. mary's": "Huskies",
  "smu": "Huskies",
  "stfx": "X-Men",
  "st. fx": "X-Men", 
  "st fx": "X-Men",
  "stfx x-men": "X-Men",
  "stfx x-women": "X-Women",
  "unb": "Reds",
  "unb reds": "Reds",
  "upei": "Panthers",
  "upei panthers": "Panthers",
  
  // Canada West
  "alberta": "Golden Bears",
  "u of a": "Golden Bears",
  "alberta golden bears": "Golden Bears",
  "alberta pandas": "Pandas",
  "brandon": "Bobcats",
  "brandon bobcats": "Bobcats",
  "calgary": "Dinos",
  "u of c": "Dinos",
  "calgary dinos": "Dinos",
  "lethbridge": "Pronghorns",
  "lethbridge pronghorns": "Pronghorns",
  "macewan": "Griffins", 
  "mac": "Griffins",
  "macewan griffins": "Griffins",
  "manitoba": "Bisons",
  "u of m": "Bisons",
  "manitoba bisons": "Bisons",
  "mount royal": "Cougars",
  "mru": "Cougars",
  "mount royal cougars": "Cougars",
  "regina": "Cougars",
  "regina cougars": "Cougars",
  "saskatchewan": "Huskies",
  "u of s": "Huskies", 
  "sask": "Huskies",
  "saskatchewan huskies": "Huskies",
  "thompson rivers": "WolfPack",
  "tru": "WolfPack",
  "thompson rivers wolfpack": "WolfPack", 
  "trinity western": "Spartans",
  "twu": "Spartans",
  "trinity western spartans": "Spartans",
  "ubc": "Thunderbirds",
  "ubc thunderbirds": "Thunderbirds",
  "ubc okanagan": "Heat",
  "ubco": "Heat",
  "ubc okanagan heat": "Heat",
  "ufv": "Cascades",
  "fraser valley": "Cascades",
  "ufv cascades": "Cascades",
  "unbc": "Timberwolves", 
  "unbc timberwolves": "Timberwolves",
  "victoria": "Vikes",
  "uvic": "Vikes",
  "victoria vikes": "Vikes",
  "winnipeg": "Wesmen",
  "winnipeg wesmen": "Wesmen",
  
  // OUA
  "algoma": "Thunderbirds",
  "algoma thunderbirds": "Thunderbirds",
  "brock": "Badgers",
  "brock badgers": "Badgers",
  "carleton": "Ravens",
  "carleton ravens": "Ravens",
  "guelph": "Gryphons",
  "guelph gryphons": "Gryphons",
  "lakehead": "Thunderwolves",
  "lakehead thunderwolves": "Thunderwolves",
  "laurentian": "Voyageurs",
  "laurentian voyageurs": "Voyageurs",
  "mcmaster": "Marauders",
  "mac": "Marauders",
  "mcmaster marauders": "Marauders",
  "nipissing": "Lakers",
  "nipissing lakers": "Lakers",
  "ontario tech": "Ridgebacks",
  "uoit": "Ridgebacks",
  "ontario tech ridgebacks": "Ridgebacks",
  "ottawa": "Gee-Gees",
  "uottawa": "Gee-Gees",
  "ottawa gee-gees": "Gee-Gees",
  "queen's": "Gaels",
  "queens": "Gaels",
  "queen's gaels": "Gaels",
  "toronto": "Varsity Blues",
  "u of t": "Varsity Blues",
  "toronto varsity blues": "Varsity Blues",
  "toronto metropolitan": "Bold",
  "tmu": "Bold",
  "ryerson": "Bold",
  "tmu bold": "Bold",
  "waterloo": "Warriors",
  "waterloo warriors": "Warriors",
  "western": "Mustangs",
  "western mustangs": "Mustangs",
  "wilfrid laurier": "Golden Hawks",
  "laurier": "Golden Hawks",
  "wlu": "Golden Hawks",
  "wilfrid laurier golden hawks": "Golden Hawks",
  "windsor": "Lancers",
  "windsor lancers": "Lancers",
  "york": "Lions",
  "york lions": "Lions",
  
  // RSEQ
  "bishop's": "Gaiters",
  "bishops": "Gaiters",
  "bishop's gaiters": "Gaiters",
  "concordia": "Stingers",
  "concordia stingers": "Stingers",
  "laval": "Rouge et Or",
  "laval rouge et or": "Rouge et Or",
  "mcgill": "Redbirds",
  "mcgill redbirds": "Redbirds",
  "mcgill martlets": "Martlets",
  "uqam": "Citadins",
  "uqam citadins": "Citadins"
};

module.exports = teamMappings;